name: Python Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7,3.8,3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
g
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: auto-wg-gesucht

      - name: Lint with flake8
        run: |
          pip install --upgrade pip
          pip install flake8
          flake8 src/ --ignore=E501,W504,E128